import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ふろんとらいん</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ふろんとらいん
        </h1>

        <p className={styles.description}>
          ふろん(@Focus_Sash)のブログです
        </p>

        <div className={styles.grid}>
          <a href="/hubs/misc" className={styles.card}>
            <h2>雑多な記事</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="/hubs/learning" className={styles.card}>
            <h2>勉強したこと</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="/hubs/creations"
            className={styles.card}
          >
            <h2>作ったもの</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="/hubs/reviwes"
            className={styles.card}
          >
            <h2>感想とか</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>

          <a
            href="/hubs/recent"
            className={styles.card}
          >
            <h2>最近の記事</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="/hubs/tags"
            className={styles.card}
          >
            <h2>タグ一覧</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
